print()
print("STAR WARS NAME GENERATOR")
print()
print("Enter your first name: ")
firstname = input().strip().capitalize()
print("Enter your last name: ")
lastname = input().strip().lower()
print("Enter your mom's maiden name: ")
maidename = input().strip().capitalize()
print("Enter the city where you were born: ")
city = input().strip().lower()
print()
print(f"Your Star Wars name is: {firstname[0:3]}{lastname[0:2]} {maidename[0:2]}{city[-3:]}")
